# Generated by Django 5.0.6 on 2025-03-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='kubot_ai.wallet'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='kubot_ai.wallet'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubot_ai.wallet'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubot_ai.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
