# Generated by Django 5.0.6 on 2025-03-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0002_alter_referral_referred_user_alter_referral_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(default='', editable=False, max_length=6, unique=True),
        ),
    ]
