# Generated by Django 5.0.6 on 2025-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0003_referral_referral_id_wallet_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(default='PQ0116', editable=False, max_length=6, unique=True),
        ),
    ]
