# Generated by Django 5.0.6 on 2025-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0004_alter_wallet_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(default='606238', editable=False, max_length=6, unique=True),
        ),
    ]
