# Generated by Django 5.0.6 on 2025-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0005_alter_task_task_type_alter_wallet_referral_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='task',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
