# Generated by Django 5.0.6 on 2025-03-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kubot_ai', '0006_remove_reward_task_remove_reward_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(max_length=50)),
                ('reward_amount', models.IntegerField(default=0)),
                ('partner_project', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255, unique=True)),
                ('eth_address', models.CharField(max_length=255, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('referral_id', models.CharField(default='5V4909', editable=False, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubot_ai.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubot_ai.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kubot_ai.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubot_ai.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(blank=True, max_length=6, null=True)),
                ('reward_amount', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='kubot_ai.wallet')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='kubot_ai.wallet')),
            ],
        ),
    ]
