# Generated by Django 5.0.6 on 2025-03-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(default='FMW897', editable=False, max_length=6, unique=True),
        ),
    ]
