# Generated by Django 5.0.6 on 2025-03-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubot_ai', '0009_alter_wallet_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(default='OWH100', editable=False, max_length=6, unique=True),
        ),
    ]
